/**
 * Seed list de livres français pour l'Explorer
 * Garantit un feed français de qualité avec des livres connus
 */
export const FRENCH_EXPLORER_SEED_LIST = [
  // Classiques français
  "Le Rouge et le Noir",
  "L'Étranger",
  "Les Misérables",
  "Madame Bovary",
  "Germinal",
  "L'Écume des jours",
  "La Peste",
  "Candide",
  "Le Petit Prince",
  "Le Comte de Monte-Cristo",
  "Les Trois Mousquetaires",
  "Vingt mille lieues sous les mers",
  "Notre-Dame de Paris",
  "Bel-Ami",
  "Le Père Goriot",
  "L'Assommoir",
  "Nana",
  "Au bonheur des dames",
  "Thérèse Raquin",
  "Le Horla",
  "Boule de suif",
  "Une vie",
  "Pierre et Jean",
  "Le Rouge et le Noir",
  "La Chartreuse de Parme",
  "Le Grand Meaulnes",
  "Le Silence de la mer",
  "Voyage au bout de la nuit",
  "L'Étranger",
  "La Peste",
  "L'Étranger",
  "Le Mythe de Sisyphe",
  "La Chute",
  "L'Exil et le royaume",
  "Le Premier Homme",
  "Bonjour tristesse",
  "Les Mandarins",
  "L'Invitée",
  "Le Deuxième Sexe",
  "Les Mots",
  "La Nausée",
  "Hubert Reeves nous explique",
  "Sapiens",
  "21 leçons pour le XXIe siècle",
  "Homo Deus",
  "Le Seigneur des anneaux",
  "Harry Potter",
  "1984",
  "Dune",
  "Lolita",
  "Le Parrain",
  "Crime et Châtiment",
  "Guerre et Paix",
  "Anna Karénine",
  "L'Idiot",
  "Les Frères Karamazov",
  "Le Maître et Marguerite",
  "Cent ans de solitude",
  "L'Amour aux temps du choléra",
  "Le Vieil Homme et la mer",
  "Pour qui sonne le glas",
  "L'Attrape-cœurs",
  "Le Meilleur des mondes",
  "Fahrenheit 451",
  "Le Guépard",
  "Le Nom de la rose",
  "Millénium",
  "La Trilogie du mal",
  "Le Château",
  "Le Procès",
  "La Métamorphose",
  "L'Étranger",
  "Le Parfum",
  "Le Liseur",
  "La Femme qui attendait",
  "La Vie devant soi",
  "L'Art de perdre",
  "La Petite Fille de Monsieur Linh",
  "L'Élégance du hérisson",
  "La Clé de Sarah",
  "Le Chardonneret",
  "La Servante écarlate",
  "Le Test",
  "L'Anomalie",
  "La Plus secrète mémoire des hommes",
  "Leurs enfants après eux",
  "L'Art français de la guerre",
  "HHhH",
  "La Carte et le Territoire",
  "Sérotonine",
  "Soumission",
  "Les Particules élémentaires",
  "Plateforme",
  "Extension du domaine de la lutte",
  "La Possibilité d'une île",
  "Lanzarote",
  "La Carte et le Territoire",
  "Sérotonine",
  "Soumission",
  "Les Particules élémentaires",
  "Plateforme",
  "Extension du domaine de la lutte",
  "La Possibilité d'une île",
  "Lanzarote",
  "La Carte et le Territoire",
  "Sérotonine",
  "Soumission",
  "Les Particules élémentaires",
  "Plateforme",
  "Extension du domaine de la lutte",
  "La Possibilité d'une île",
  "Lanzarote",
  "La Carte et le Territoire",
  "Sérotonine",
  "Soumission",
  "Les Particules élémentaires",
  "Plateforme",
  "Extension du domaine de la lutte",
  "La Possibilité d'une île",
  "Lanzarote",
  "La Carte et le Territoire",
  "Sérotonine",
  "Soumission",
  "Les Particules élémentaires",
  "Plateforme",
  "Extension du domaine de la lutte",
  "La Possibilité d'une île",
  "Lanzarote",
  "La Carte et le Territoire",
  "Sérotonine",
  "Soumission",
  "Les Particules élémentaires",
  "Plateforme",
  "Extension du domaine de la lutte",
  "La Possibilité d'une île",
  "Lanzarote",
  "La Carte et le Territoire",
  "Sérotonine",
  "Soumission",
  "Les Particules élémentaires",
  "Plateforme",
  "Extension du domaine de la lutte",
  "La Possibilité d'une île",
  "Lanzarote",
];

